version: "3.8"

services:

  ecommerce_web:
    build: ./ECommerceWeb
    container_name: ecommerce-nx-web
    environment:
      API_BASE_URL: "http://localhost:8080/"
    ports:
      - 4200:80
    depends_on:
      - ecommerce_service

  ecommerce_service:
    build: ./ECommerceService/ecommerce-backend
    restart: always
    ports:
      - 8080:8080
    networks:
      - ecommerce-internal-network
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false   
    depends_on:
      - ecommerce_db    

  ecommerce_db:
    image: mysql:latest
    container_name: ecommerce-mysqldb
    restart: unless-stopped
    volumes:
      - ./ECommerceDatabase/scripts/schema.sql:/docker-entrypoint-initdb.d/01.sql
      - ./ECommerceDatabase/scripts/data.sql:/docker-entrypoint-initdb.d/02.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - ecommerce-internal-network

networks:
  ecommerce-internal-network:
