version: "3.8"
name: ecommerce-docker-containers
services:
  ecommerce_db:
    image: shubhanjanweb/ecommerce-database-image:latest
    container_name: ecommerce-database-container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - ecommerce-network

  ecommerce_backend:
    image: shubhanjanweb/ecommerce-backend-image:latest
    container_name: ecommerce-backend-container
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:mysql://ecommerce-database-container:3306/ecommerce?useSSL=false
    depends_on:
      - ecommerce_db
    links:
      - ecommerce_db
    networks:
      - ecommerce-network

  ecommerce_web:
    image: shubhanjanweb/ecommerce-web-image:latest
    container_name: app-web
    restart: unless-stopped
    ports:
      - 4200:80
    environment:
      API_BASE_URL: http://localhost:8080
    depends_on:
      - ecommerce_backend
    links:
      - ecommerce_backend
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    name: ecommerce-network
