version: "3.8"

services:
  ecommerce_db:
    build: ./ECommerceService/ecommerce-database
    container_name: ecommerce-database-container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - ecommerce-network

  ecommerce_service:
    build: ./ECommerceService/ecommerce-backend
    container_name: ecommerce-service-container
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:mysql://ecommerce-database-container:3306/ecommerce?useSSL=false
    depends_on:
      - ecommerce_db
    links:
      - ecommerce_db
    networks:
      - ecommerce-network

  ecommerce_web:
    build: ./ECommerceWeb
    container_name: app-web
    restart: unless-stopped
    ports:
      - 4200:80
    environment:
      API_BASE_URL: http://localhost:8080
    depends_on:
      - ecommerce_service
    links:
      - ecommerce_service
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
