name: Database Build CI

on:
  push:
    branches: ["main"]
    paths:
      - "Code/ECommerceService/ecommerce-database/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Code/ECommerceService/ecommerce-database/**"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Code/ECommerceService/ecommerce-database
      image-name: ecommerce-database-image
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.working-directory }}
          dockerfile: ${{ env.working-directory }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.image-name }}:latest
