# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
    - 'Code/ECommerceWeb/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'Code/ECommerceWeb/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Build and Push Container Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: dockerfile
        repository: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
        tag_with_ref: true
        tag_with_sha: true
             
